spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
  # /myProduct/product/list -> /product/product/list
    aaaaaa:
      path: /system/**
      serviceId: client-system
      sensitiveHeaders:
  #简洁写法
#    product: /myProduct/**
management:
  security:
    enabled: false
