spring:
  application:
    name: client
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chinapost-order?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true
    username: wxjk
    password: wxjk
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
